use_frameworks!

platform :ios, '9.0'

target 'SectionName_Example' do
  pod 'SectionName', :path => '../'

  target 'SectionName_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
